server {
  listen 443 ssl default_server;
  server_name github-checker.arthurka-localhost.com;
  include conf.d/github-checker_common.nginx;
  include conf.d/config_raw-ip-redirect.nginx;
  if ($host != $server_name) {
    return 308 https://github-checker.arthurka-localhost.com$request_uri;
  }

  ssl_certificate /mkcert/github-checker-cert.pem;
  ssl_certificate_key /mkcert/github-checker-cert-key.pem;

  location /api/ {
    rewrite ^/api/?(.*)$ /$1 break;
    proxy_pass $api_upstream;
  }
  location / {
    proxy_pass $api_upstream;
  }
}
