server {
  listen 443 ssl;
  server_name github-checker.arthurka.com;
  include conf.d/github-checker_common.nginx;

  ssl_certificate /etc/letsencrypt/live/github-checker.arthurka.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/github-checker.arthurka.com/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/github-checker.arthurka.com/chain.pem;
  ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

  location /api/ {
    rewrite ^/api/?(.*)$ /$1 break;
    proxy_pass $api_upstream;
  }
  location / {
    proxy_pass $api_upstream;
  }
}
